spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sas-bank
    username: postgres
    password: postgresuser
  mvc:
    servlet:
      path: /restapi


  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
