spring:
  config:
    import: classpath:environments/
  profiles:
    active: local
  mvc:
    servlet:
      path: /restapi
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
